<a href="https://colab.research.google.com/github/Raxmatulloh00/Week_Lab3/blob/main/exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Fundamentals Exercises

This notebook contains exercises based on the PyTorch Fundamentals tutorial. Each section corresponds to a topic from the original notebook. Complete the exercises by filling in the code cells where indicated.

## 1. Introduction to Tensors

### Exercise 1.1: Create a scalar tensor
Create a scalar tensor with the value 42 and print its value, number of dimensions (ndim), and shape.

In [1]:
import torch

# Create a scalar tensor
scalar = torch.tensor(42)

# Print details
print(scalar)
print(f"Number of dimensions: {scalar.ndim}")
print(f"Shape: {scalar.shape}")

tensor(42)
Number of dimensions: 0
Shape: torch.Size([])


### Exercise 1.2: Create a vector tensor
Create a vector tensor with values [1, 2, 3, 4] and print its value, ndim, and shape.

In [2]:
import torch

# Create a vector tensor
vector = torch.tensor([1, 2, 3, 4])

# Print details
print(vector)
print(f"Number of dimensions: {vector.ndim}")
print(f"Shape: {vector.shape}")

tensor([1, 2, 3, 4])
Number of dimensions: 1
Shape: torch.Size([4])


### Exercise 1.3: Create a matrix tensor
Create a 2x3 matrix tensor with values [[1, 2, 3], [4, 5, 6]] and print its details.

In [3]:
import torch

# Create a matrix tensor (2 rows, 3 columns)
matrix = torch.tensor([[1, 2, 3],
                       [4, 5, 6]])

# Print details
print(matrix)
print(f"Number of dimensions: {matrix.ndim}")
print(f"Shape: {matrix.shape}")

tensor([[1, 2, 3],
        [4, 5, 6]])
Number of dimensions: 2
Shape: torch.Size([2, 3])


### Exercise 1.4: Create a 3D tensor
Create a tensor of shape (2, 2, 2) with sequential values from 1 to 8 using torch.arange and reshape.

In [10]:
import torch

# Create a 3D tensor with values 1 to 8
tensor_3d = torch.arange(1, 9).reshape(2, 2, 2)

# Print details
print(tensor_3d)
print(f"Number of dimensions: {tensor_3d.ndim}")
print(f"Shape: {tensor_3d.shape}")

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Number of dimensions: 3
Shape: torch.Size([2, 2, 2])


## 2. Random Tensors

### Exercise 2.1: Create a random tensor
Create a random tensor of shape (4, 4) and print it along with its dtype.

In [4]:
# TODO: Create random tensor
random_tensor = torch.rand(size=(3, 4))

print(random_tensor)
print(f"Datatype: {random_tensor.dtype}")

tensor([[0.9392, 0.7047, 0.9655, 0.3942],
        [0.9318, 0.4366, 0.6957, 0.8156],
        [0.1679, 0.7709, 0.6220, 0.1907]])
Datatype: torch.float32


### Exercise 2.2: Create an image-sized random tensor
Create a random tensor of shape (3, 224, 224) simulating an image (channels, height, width).

In [9]:
# TODO: Create image-sized random tensor
image_tensor = torch.rand(size=(3, 224, 224))


print(f"Shape: {image_tensor.shape}")

Shape: torch.Size([3, 224, 224])


## 3. Zeros and Ones

### Exercise 3.1: Create a tensor of zeros
Create a tensor of zeros with shape (5, 5).

In [11]:
# TODO: Create zeros tensor
zeros = torch.zeros(size=(5, 5))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]),
 torch.float32)

### Exercise 3.2: Create a tensor of ones like another tensor
Create a random tensor of shape (3, 3), then create a tensor of ones with the same shape using ones_like.

In [22]:
# Create ones like random_tensor
random_tensor = torch.rand(3, 3)

ones_like = torch.ones_like(random_tensor)

print("Random Tensor:")
print(random_tensor)

print("\nOnes Like Tensor:")
print(ones_like)

Random Tensor:
tensor([[0.3511, 0.6903, 0.3713],
        [0.1985, 0.3804, 0.3355],
        [0.6377, 0.3522, 0.7702]])

Ones Like Tensor:
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


## 4. Creating Ranges

### Exercise 4.1: Create a range tensor
Create a tensor with values from 0 to 20 with a step of 2 using torch.arange.

In [23]:
# Create range tensor from 0 to 20 with step 2
range_tensor = torch.arange(0, 21, 2)

print(range_tensor)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])


## 5. Tensor Datatypes

### Exercise 5.1: Create tensors with specific dtypes
Create a tensor with values [1.0, 2.0, 3.0] using dtype=torch.float16 and another with dtype=torch.int64.

In [24]:
import torch

# float16 tensor
float16_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float16)

# int64 tensor
int64_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.int64)

print("Float16 Tensor:")
print(float16_tensor)
print(float16_tensor.dtype)

print("\nInt64 Tensor:")
print(int64_tensor)
print(int64_tensor.dtype)

Float16 Tensor:
tensor([1., 2., 3.], dtype=torch.float16)
torch.float16

Int64 Tensor:
tensor([1, 2, 3])
torch.int64


### Exercise 5.2: Change dtype
Convert the float16_tensor to float32.

In [25]:
# TODO: Change dtype


# Original float16 tensor
float16_tensor = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float16)

# Change dtype to float32
float32_tensor = float16_tensor.to(torch.float32)

print("Original dtype:", float16_tensor.dtype)
print("Converted dtype:", float32_tensor.dtype)

Original dtype: torch.float16
Converted dtype: torch.float32


## 6. Getting Information from Tensors

### Exercise 6.1: Print tensor info
Create a random tensor of shape (2, 3, 4) and print its shape, dtype, and device.

In [26]:
# TODO: Create tensor and print info
info_tensor = torch.rand(2, 3, 4)

# Print details
print("Shape:", info_tensor.shape)
print("Dtype:", info_tensor.dtype)
print("Device:", info_tensor.device)

Shape: torch.Size([2, 3, 4])
Dtype: torch.float32
Device: cpu


## 7. Manipulating Tensors (Basic Operations)

### Exercise 7.1: Perform basic operations
Create a tensor [10, 20, 30]. Add 5, subtract 10, multiply by 2, and divide by 10.

In [27]:
tensor = torch.tensor([10, 20, 30])
# TODO: Add 5
tensor + 5
# TODO: Subtract 10

# TODO: Multiply by 2

# TODO: Divide by 10

tensor([15, 25, 35])

In [28]:
tensor - 10

tensor([ 0, 10, 20])

In [29]:
tensor * 2

tensor([20, 40, 60])

In [30]:
tensor / 10

tensor([1., 2., 3.])

### Exercise 7.2: Matrix multiplication
Create two tensors A (2x3) and B (3x2) with random values and perform matrix multiplication.

In [32]:
# TODO: Create A and B
A = torch.rand(2, 3)
B = torch.rand(3, 2)

# TODO: Matrix mul using torch.mm
result_mm = A @ B

# TODO: Matrix mul using @
result_at = torch.matmul(A, B)

print("Tensor A:")
print(A)
print("\nTensor B:")
print(B)
print("\nResult using @:")
print(result_mm)
print("\nResult using torch.matmul:")
print(result_at)

Tensor A:
tensor([[0.0421, 0.9934, 0.7881],
        [0.0585, 0.2612, 0.6008]])

Tensor B:
tensor([[0.5195, 0.8618],
        [0.9343, 0.4341],
        [0.7722, 0.8010]])

Result using @:
tensor([[1.5586, 1.0987],
        [0.7384, 0.6450]])

Result using torch.matmul:
tensor([[1.5586, 1.0987],
        [0.7384, 0.6450]])


## 8. Tensor Aggregation

### Exercise 8.1: Find min, max, mean, sum
Create a tensor with values from 0 to 100 and find its min, max, mean, and sum.

In [40]:
agg_tensor = torch.arange(0, 101)
# TODO: Min
min = agg_tensor.min()
# TODO: Max
max = agg_tensor.max()
# TODO: Mean (note: may need to cast to float)
mean = agg_tensor.float().mean()
# TODO: Sum
sum = agg_tensor.sum()


print("Tensor:", agg_tensor)
print("Min:", min.item())
print("Max:", max.item())
print("Mean:", mean.item())
print("Sum:", sum.item())

Tensor: tensor([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
         28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
         42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
         56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
         70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
         84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
         98,  99, 100])
Min: 0
Max: 100
Mean: 50.0
Sum: 5050


### Exercise 8.2: Argmin and argmax
Find the positions of the minimum and maximum values in the above tensor.

In [42]:
agg_tensor = torch.arange(0, 101)
# TODO: Argmin
min = agg_tensor.argmin()
# TODO: Argmax
max = agg_tensor.argmax()

print("Tensor:", agg_tensor)
print("Index of min value:", min.item())
print("Index of max value:", max.item())

Tensor: tensor([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
         14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
         28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,
         42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
         56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,  67,  68,  69,
         70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
         84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95,  96,  97,
         98,  99, 100])
Index of min value: 0
Index of max value: 100


## 9. Reshaping, Stacking, Squeezing, Unsqueezing

### Exercise 9.1: Reshape a tensor
Create a tensor of shape (10,) and reshape it to (2, 5).

In [44]:
reshape_tensor = torch.arange(10)
# TODO: Reshape
reshaped = reshape_tensor.reshape(2, 5)

print(reshaped)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


### Exercise 9.2: Stack tensors
Create two tensors of shape (2, 2) and stack them vertically and horizontally.

In [45]:
tensor1 = torch.rand(2, 2)
tensor2 = torch.rand(2, 2)
# TODO: Stack vertically (dim=0)
vertical_stack = torch.vstack((tensor1, tensor2))
# TODO: Stack horizontally (dim=1)
horizontal_stack = torch.hstack((tensor1, tensor2))

print("Tensor 1:\n", tensor1)
print("Tensor 2:\n", tensor2)
print("Vertical Stack:\n", vertical_stack)
print("Horizontal Stack:\n", horizontal_stack)

Tensor 1:
 tensor([[0.4867, 0.4894],
        [0.3041, 0.0516]])
Tensor 2:
 tensor([[0.9587, 0.4262],
        [0.2733, 0.6296]])
Vertical Stack:
 tensor([[0.4867, 0.4894],
        [0.3041, 0.0516],
        [0.9587, 0.4262],
        [0.2733, 0.6296]])
Horizontal Stack:
 tensor([[0.4867, 0.4894, 0.9587, 0.4262],
        [0.3041, 0.0516, 0.2733, 0.6296]])


### Exercise 9.3: Squeeze and unsqueeze
Create a tensor of shape (1, 3, 1), squeeze it, then unsqueeze it back on dim=0.

In [47]:
squeeze_tensor = torch.rand(1, 3, 1)
# TODO: Squeeze
squeezed = squeeze_tensor.squeeze()
# TODO: Unsqueeze on dim=0
unsqueezed = squeezed.unsqueeze(0)

print("Original tensor shape:", squeeze_tensor.shape)
print("Squeezed tensor shape:", squeezed.shape)
print("Unsqueezed tensor shape:", unsqueezed.shape)

Original tensor shape: torch.Size([1, 3, 1])
Squeezed tensor shape: torch.Size([3])
Unsqueezed tensor shape: torch.Size([1, 3])


### Exercise 9.4: Permute
Create an image tensor (3, 100, 100) and permute it to (100, 100, 3).

In [7]:
image_tensor = torch.rand(3, 100, 100)
# TODO: Permute
permuted = image_tensor.permute(1, 2, 0)


print("Original shape:", image_tensor.shape)
print("Permuted shape:", permuted.shape)

Original shape: torch.Size([3, 100, 100])
Permuted shape: torch.Size([100, 100, 3])


## 10. Indexing

### Exercise 10.1: Index into a tensor
Create a tensor [[[1,2,3],[4,5,6],[7,8,9]]] and index to get 5, then the entire second row.

In [49]:
index_tensor = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]]])
# TODO: Get 5
element_5 = index_tensor[0, 1, 1]
# TODO: Get second row [4,5,6]
second_row = index_tensor[0, 1, :]


print("Element 5:", element_5)
print("Second row:", second_row)

Element 5: tensor(5)
Second row: tensor([4, 5, 6])


## 11. PyTorch and NumPy

### Exercise 11.1: NumPy to PyTorch
Create a NumPy array [1,2,3,4] and convert it to a PyTorch tensor.

In [50]:
import numpy as np
numpy_array = np.array([1,2,3,4])
# TODO: Convert to tensor
from_numpy = torch.from_numpy(numpy_array)

print("NumPy array:", numpy_array)
print("PyTorch tensor:", from_numpy)

NumPy array: [1 2 3 4]
PyTorch tensor: tensor([1, 2, 3, 4])


### Exercise 11.2: PyTorch to NumPy
Create a PyTorch tensor [5,6,7,8] and convert it to a NumPy array.

In [51]:
pytorch_tensor = torch.tensor([5,6,7,8])
# TODO: Convert to NumPy
to_numpy = pytorch_tensor.numpy()

print("PyTorch tensor:", pytorch_tensor)
print("NumPy array:", to_numpy)

PyTorch tensor: tensor([5, 6, 7, 8])
NumPy array: [5 6 7 8]


## 12. Reproducibility

### Exercise 12.1: Set manual seed
Set the manual seed to 77 and create two random tensors of shape (2,2). Check if they are equal.

In [54]:
# TODO: Set seed
torch.manual_seed(77)
rand1 = torch.rand(2,2)

# TODO: Reset seed for second tensor
torch.manual_seed(77)
rand2 = torch.rand(2,2)

# Check equality
are_equal = torch.equal(rand1, rand2)

print("Tensor 1:\n", rand1)
print("Tensor 2:\n", rand2)
print(rand1 == rand2)

Tensor 1:
 tensor([[0.2919, 0.2857],
        [0.4021, 0.4645]])
Tensor 2:
 tensor([[0.2919, 0.2857],
        [0.4021, 0.4645]])
tensor([[True, True],
        [True, True]])


## 13. Running on GPUs

### Exercise 13.1: Check for GPU
Write code to check if CUDA is available and set the device accordingly.

In [6]:
# TODO: Set device
import torch
torch.cuda.is_available()

True

### Exercise 13.2: Move tensor to GPU
Create a tensor and move it to the GPU if available. Then move it back to CPU and convert to NumPy.

In [1]:
!nvidia-smi

Thu Feb 19 05:48:08 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   39C    P8              9W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [5]:
gpu_tensor = torch.tensor([10, 20, 30])

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# TODO: Move to device
gpu_tensor = gpu_tensor.to(device)

# TODO: Move back to CPU and to NumPy
cpu_numpy = gpu_tensor.cpu().numpy()


print("Tensor on device:", gpu_tensor)
print("NumPy array on CPU:", cpu_numpy)

Tensor on device: tensor([10, 20, 30], device='cuda:0')
NumPy array on CPU: [10 20 30]
